name: "🐞 General Bug report"
description: Create a general bug report to help us improve
title: "[GENERAL BUG] A short description here."
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to help us understand and fix your bug faster.
        - **Level:** [see issue priorities](https://github.com/Investec-Developer-Community/.github/blob/main/.github/ISSUE_TEMPLATE/issue-priorities)
  - type: dropdown
    id: level
    attributes:
      label: Level
      description: What is the priority of this issue?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug.
      placeholder: e.g. When I try to Auth, I get a 404 error.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Please list the steps needed to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
      placeholder: e.g. The user dashboard should load successfully.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened?
      placeholder: e.g. I got an error page instead.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details or context you'd like to provide, like screenshots, logs, etc.
      placeholder: Add any other context, screenshots, or error logs here.
    validations:
      required: false
