name: Export Community Builds to JSON

on:
  schedule:
    - cron: '0 * * * *' # hourly
  workflow_dispatch:

jobs:
  export-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch and parse issues into enriched JSON
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs

          echo "Fetching issues from GitHub..."
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               "https://api.g
