name: Export Community Builds to JSON

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  export-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch issues via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/Investec-Developer-Community/.github/issues?labels=New%20Community%20Build&state=open&per_page=100" \
               > docs/builds.json

      - name: Commit builds.json
        run: |
          git config user.name "Investec Bot"
          git config user.email "bot@investec.com"
          git add docs/builds.json
          git diff --cached --quiet || git commit -m "Update community builds JSON"
          git push
